---
# yaml-language-server: $schema=./schemas/v1/standards.schema.json
version: 1
extends:
  - git:
      repository: https://github.com/nlecoy/standards-old
      revision:
        branch: chore/pull
      path: .standards.yml
rules:
  - id: clickhouse.nullable-columns
    description: Avoid nullable columns
    rationale: >
      Nullable column (e.g. Nullable(String)) creates a separate column of UInt8 type.
      This additional column has to be processed every time a user works with a Nullable column.
      This leads to additional storage space used and almost always negatively affects performance.
    level: SHOULD NOT
    applies_to:
      include:
        - "**/*.sql"
    references:
      - https://clickhouse.com/docs/concepts/best-practices/avoidnullablecolumns
